services:
  garmin-fetch-data:
    restart: unless-stopped
    image: ghcr.io/harpesichord/garmin-grafana:latest
    container_name: garmin-fetch-data
    depends_on:
      - influxdb
    volumes:
      - ./garminconnect-tokens:/home/appuser/.garminconnect # (persistant tokens storage - garminconnect-tokens folder must be owned by 1000:1000)
    environment:
      # Choose InfluxDB version - set to "1" for InfluxDB v1, "2" for InfluxDB v2
      - INFLUXDB_VERSION=2
      
      # InfluxDB v2 configuration
      - INFLUXDB_V2_URL=http://influxdb:8086
      - INFLUXDB_V2_ORG=my-org
      - INFLUXDB_V2_TOKEN=my-token
      - INFLUXDB_V2_BUCKET=garmin
      
      # InfluxDB v1 configuration (used only if INFLUXDB_VERSION=1)
      # - INFLUXDB_HOST=influxdb
      # - INFLUXDB_PORT=8086
      # - INFLUXDB_USERNAME=influxdb_user
      # - INFLUXDB_PASSWORD=influxdb_secret_password
      # - INFLUXDB_DATABASE=garmin
      # - INFLUXDB_SSL=false
      
      - UPDATE_INTERVAL_SECONDS=300
      - LOG_LEVEL=INFO

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=garmin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    image: 'influxdb:2.7'
    # For InfluxDB v1, uncomment the following and comment out the above:
    # environment:
    #   - INFLUXDB_DB=garmin
    #   - INFLUXDB_USER=influxdb_user
    #   - INFLUXDB_USER_PASSWORD=influxdb_secret_password
    #   - INFLUXDB_DATA_INDEX_VERSION=tsi1
    # volumes:
    #   - influxdb_data:/var/lib/influxdb
    # image: 'influxdb:1.11'

  grafana:
    restart: unless-stopped
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'
    image: 'grafana/grafana:latest'

volumes:
  influxdb_data:
  grafana_data:
