services:
  garmin-fetch-data:
    restart: unless-stopped
    image: ghcr.io/harpesichord/garmin-grafana:latest
    container_name: garmin-fetch-data
    depends_on:
      - influxdb
    volumes:
      - ./garminconnect-tokens:/home/appuser/.garminconnect # (persistant tokens storage - garminconnect-tokens folder must be owned by 1000:1000)
    environment:
      - INFLUXDB_V2_URL=http://influxdb:8086
      - INFLUXDB_V2_ORG=my-org
      - INFLUXDB_V2_TOKEN=my-token
      - INFLUXDB_BUCKET=garmin
      - UPDATE_INTERVAL_SECONDS=300
      - LOG_LEVEL=INFO

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=garmin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    image: 'influxdb:2.7'

  grafana:
    restart: unless-stopped
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'
    image: 'grafana/grafana:latest'

volumes:
  influxdb_data:
  grafana_data:
